export const DETAILED_MOVIE_UPDATE = "DETAILED_MOVIE_UPDATE";
export const DETAILED_MOVIE_FETCHING = "DETAILED_MOVIE_FETCHING";
export const DETAILED_MOVIE_FAVORITE_TOGGLE = "DETAILED_MOVIE_FAVORITE_TOGGLE";
