export const POPULAR_MOVIES_UPDATE_LIST = "POPULAR_MOVIES_UPDATE_LIST";
export const POPULAR_MOVIES_FETCHING = "POPULAR_MOVIES_FETCHING";
export const POPULAR_MOVIES_UPDATE_SELECTED = "POPULAR_MOVIES_UPDATE_SELECTED";
